name: fetch
on:
  schedule:
    - cron: '30 */3 * * *' # At minute 30 past every 3rd hour.
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fetch:
    name: Fetch
    if: github.repository_owner == 'denysdovhan'
    runs-on: ubuntu-latest
    steps:
      - name: ‚¨áÔ∏è Checkout Repo
        uses: actions/checkout@v3

      - name: ‚¨° Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm

      - name: ‚¨áÔ∏è Install dependencies
        run: npm ci

      - name: ‚ö°Ô∏è Fetch data
        run: npm start

      - name: üì§ Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore(fetch): Scheduled data fetch [skip ci]'
          file_pattern: 'outages/**'
          commit_options: '--no-verify'
