name: fetch
on:
  schedule:
    - cron: '30 * * * *' # Every hour on 30th minute
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fetch:
    name: Fetch
    if: github.repository_owner == 'denysdovhan'
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout Repo
        uses: actions/checkout@v3

      - name: â¬¡ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm

      - name: â¬‡ï¸ Install dependencies
        run: npm ci

      - name: ğŸ“¥ Fetch data
        run: npm start

      - name: ğŸ“¤ Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore(fetch): Scheduled data fetch [skip ci]'
          commit_options: '--no-verify'